# Generated by Django 3.2.21 on 2023-10-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20231004_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='첨부 파일'),
        ),
    ]
